server:
  port: 8081

spring:
  application:
    name: flyway-test
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:./data/${spring.application.name}.db
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  # classpath*:mapper/**/*.xml为默认值，默认扫描resources/mapper目录及其子目录下所有xml文件
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    de.honoka.test.flyway.mapper: debug