server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:./build/elastic-search-test.db
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: de.honoka.sdk.util.framework.hibernate.SQLiteDialect
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  elasticsearch:
    # username: elastic
    # password: xxxxxx
    uris: http://localhost:9200
    connection-timeout: 10000
    socket-timeout: 10000

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/*.xml

logging:
  level:
    de.honoka.test.elasticsearch.dao: debug